### ISSUE TITLE
RuntimeError： CUDA out of memory

### ISSUE THREAD

**Issue by mengmen** [ayumiymk/aster.pytorch#2]
Hi, when trained, it always try allocate new memory. Do you have this problem?

**Comment by mengmen** [comment]
Traceback (most recent call last):
  File "main.py", line 230, in <module>
    main(args)
  File "main.py", line 203, in main
    evaluator.evaluate(test_loader, step=0, tfLogger=eval_tfLogger, dataset=test_dataset)
  File "/home/mly/recog/aster.pytorch/lib/evaluators.py", line 47, in evaluate
    output_dict = self._forward(input_dict)
  File "/home/mly/recog/aster.pytorch/lib/evaluators.py", line 152, in _forward
    output_dict = self.model(input_dict)
  File "/home/mly/anaconda3/envs/pytorch11/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mly/anaconda3/envs/pytorch11/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/mly/anaconda3/envs/pytorch11/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mly/recog/aster.pytorch/lib/models/model_builder.py", line 91, in forward
    rec_pred, rec_pred_scores = self.decoder.beam_search(encoder_feats, global_args.beam_width, self.eos)
  File "/home/mly/recog/aster.pytorch/lib/models/attention_recognition_head.py", line 99, in beam_search
    output, state = self.decoder(inflated_encoder_feats, state, y_prev)
  File "/home/mly/anaconda3/envs/pytorch11/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mly/recog/aster.pytorch/lib/models/attention_recognition_head.py", line 255, in forward
    alpha = self.attention_unit(x, sPrev)
  File "/home/mly/anaconda3/envs/pytorch11/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mly/recog/aster.pytorch/lib/models/attention_recognition_head.py", line 220, in forward
    sumTanh = torch.tanh(sProj + xProj)
RuntimeError: CUDA out of memory. Tried to allocate 88.00 MiB (GPU 0; 10.90 GiB total capacity; 8.53 GiB already allocated; 34.25 MiB free; 1.19 GiB cached)

**Comment by wenston2006** [comment]
@mengmen  have you solved the problem? I also came across with similar problem, the GPU memory usage was increasing till out of memory.

**Comment by mengmen** [comment]
@wenston2006 my test dataset is large, so CUDA out of memory when evaluation.

**Comment by wenston2006** [comment]
恩恩, 了解了,我把代码改了一下,问题解决了.

**Comment by huiyang865** [comment]
I also meet this issue. After debug the code, maybe the bug in the 'beam_search' function?

Then how to fix it?

**Comment by huiyang865** [comment]
@mengmen training dataset is also very large, why OOM not appears?

**Comment by Ocelot7777** [comment]
> @mengmen training dataset is also very large, why OOM not appears?

Hi, have you solved this problem?

**Comment by JasonBoy1** [comment]
d

**Comment by Verazjy** [comment]
> I also meet this issue. After debug the code, maybe the bug in the 'beam_search' function?
> 
> Then how to fix it?

 have you solved the problem? I also came across with a similar problem, the GPU memory usage was increasing till out of memory.

**Comment by Pgwsunny** [comment]
@JasonBoy1  @Ocelot7777  
have you solved the problem? I also came across with a similar problem, the GPU memory usage was increasing till out of memory.

**Comment by Agiroy4712** [comment]
have you solved the problem? I also came across with a similar problem, the GPU memory usage was increasing till out of memory.

**Comment by Agiroy4712** [comment]
> That's easy, you read the code carefully and will find a list which stores all the images. Comment out that code.

请问怎么优化呢
